### ISSUE TITLE
I get this error whenever I am about to download song.

### ISSUE THREAD

**Issue by usure** [gsteph/groove-dl#12]
Distro: Arch Linux
Python version: python2.7

I do:

python2 groove.py "a"

error:
A Grooveshark song downloader in python
by George Stephanos gaf.stephanos@gmail.com

Initializing...
Searching for 'a'...
Traceback (most recent call last):
  File "groove.py", line 206, in <module>
    print '\n'.join(l) #Print the results
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe8' in position 264: ordinal not in range(128)

**Comment by usure** [comment]
Haha never mind. I messed up something.

**Comment by gsteph** [comment]
What song is it ? (complete instructions with search query + song number)

On Tue, Jun 19, 2012 at 5:00 PM, Gregory <
reply@reply.github.com

**Comment by gsteph** [comment]
lol alright.
