### ISSUE TITLE
KeyError: 'result'

### ISSUE THREAD

**Issue by yasoob** [gsteph/groove-dl#16]
# 

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 3, in get_me
  File "groove.py", line 64, in getToken
    _token = json.JSONDecoder().decode(gzip.GzipFile(fileobj=(StringIO.StringIO(conn.getresponse().read()))).read())["result"]
# KeyError: 'result'

I got this error today while using groove-dl. I hope that you can fix this error.

**Comment by gsteph** [comment]
I hope so too. Grooveshark probably changed something again. Soon.

**Comment by yasoob** [comment]
so what are you going to do now. Are you going to update the script anytime
soon ?

**Comment by medthehatta** [comment]
The JSON we get back from grooveshark says:

```
fault:
    message: invalid client
    code: 1024
```

:fearful:

**Comment by yasoob** [comment]
@medthehatta  jacktheripper has corrected it. :+1:
