### ISSUE TITLE
IOError: Not a gzipped file

### ISSUE THREAD

**Issue by ghost** [gsteph/groove-dl#21]
When i try query a song with python groove.py 'music name'. I receive a error in line 79 of groove.py:

![image](https://f.cloud.github.com/assets/3359572/1015951/caeeeb6a-0beb-11e3-83f0-c1110416be86.png)

Any help?

Best Regards

**Comment by gsteph** [comment]
You must have used the service too much and got blocked by Grooveshark's servers since this doesn't happen here.
Change your public IP (use a proxy, if you're dynamic reboot your router)

**Comment by ghost** [comment]
Thx for the hint, i will try again later at home (I am doing it inside a Campus School)

Best Regards

**Comment by ghost** [comment]
At home everything worked out well, thx you very much for you time!
