### ISSUE TITLE
Pip Installability

### ISSUE THREAD

**Issue by Miserlou** [gsteph/groove-dl#27]
Doesn't seem like the version installed via pip works, but the version at HEAD works great. Any chance we can get that updated?

**Comment by gsteph** [comment]
It seems like the person here maintains the pip version. https://github.com/PierreRambaud/groove-dl
You could contact him.

**Comment by Miserlou** [comment]
That looks like completely different code though, and it doesn't work.

This is the good version of groove-dl - what I'm saying is, please make this installable via pip! I can package if that would help.

**Comment by gsteph** [comment]
There's a name clash and I can't ask him to remove his project off pip. I'm welcome to solutions.

PS I've just tried his product and it works.

**Comment by Miserlou** [comment]
I'd say just register a different name for your pip package.. g-dl, gsdl,
groovedown, groove.. whatever tickles your fancy!

Just something to make it easier for me to tell people to install this app.
I really like it.

ps.. I made this.. maybe it's useful for you..
https://github.com/Miserlou/SoundScrape
