### ISSUE TITLE
Multiple songs same name

### ISSUE THREAD

**Issue by ghost** [gsteph/groove-dl#29]
I've installed this (`v0.97.8` as the title says) via arch linux AUR (Version `57.b712ee9-1`) and use the GUI.
Whenever I start to download multiple files with the same name + artist at the same time (select all of them, right click, download) they somehow get mixed up into the same file instead of suffixed with (#).

Otherwise nice project :+1: 

PS: I'm your 100th:star2: :smile:

**Comment by ghost** [comment]
dammit, wrong button ^^

**Comment by gsteph** [comment]
Heh that's not supposed to happen. I'll take a look.

PS: I should have allocated some prize money for this event XD

**Comment by gsteph** [comment]
Please re-download gui.py and test.

**Comment by ghost** [comment]
Works now :smile:  Thanks!
