### ISSUE TITLE
patch: fix for missing streamKey

### ISSUE THREAD

**Issue by ioggstream** [gsteph/groove-dl#3]
diff --git a/python/groove.py b/python/groove.py
index 039bb1e..ae3c5e0 100755
--- a/python/groove.py
+++ b/python/groove.py
@@ -135,6 +135,7 @@ if **name** == "**main**":
     if songid == "" or songid == "q": exit()
     songid = eval(songid)
     stream = getStreamKeyFromSongIDEx(s[songid]["SongID"])
-    stream["result"] = stream["result"][str(s[songid]["SongID"])]
   s =  'wget --user-agent="%s" --referer=%s --post-data=streamKey=%s -O "%s - %s.mp3" "htt
   p = subprocess.Popen(s, shell=True)
   p.wait()

**Comment by gsteph** [comment]
That was already posted as a pull request. Which I accepted and then later screwed up the repo removing the request.
I'm sorry you'll have to wait until I figure out the repo issue.
Fix it locally until I do.
