### ISSUE TITLE
Index for choosing music between search results shifted

### ISSUE THREAD

**Issue by gileri** [gsteph/groove-dl#4]
WHen you enter a music title to search, the music id's (1 in this case) are shifted, ie I had to enter '0' to get the 1st result

1: "Syndicate - Nero Remix" by "Skrillex & Nero" (Syndicate)
Enter the Song ID you wish to download or (q) to exit: 1
Traceback (most recent call last):
  File "./python/groove.py", line 136, in <module>
    stream = getStreamKeyFromSongIDEx(s[songid]["SongID"])
IndexError: list index out of range

**Comment by gsteph** [comment]
Thanks for reporting this. It's been fixed.
