### ISSUE TITLE
Newest commit broke everything

### ISSUE THREAD

**Issue by DelusionalLogic** [gsteph/groove-dl#9]
The script is never able to get a stream key after the switch to getStreamKey...

It always return empty, and the program therefore exits. I can access grooveshark in browser, just not in script. (search and everything works fine, just not StreakKey

**Comment by gsteph** [comment]
Woops. I thought that was because I was banned. Sorry I'll try fixing it now.

**Comment by DelusionalLogic** [comment]
They didn't switch from the IDEx function, it seems like they use the IDs one sometimes. ill search through the swf

**Comment by gsteph** [comment]
It actually works here. o.O

**Comment by gsteph** [comment]
I changed what the stream key function returns. Could it be that you're using the 'library' from your own code and didn't change yours ?

**Comment by DelusionalLogic** [comment]
I forked your code, cloned it with github for windows (cuz i'm a lazy SoaB) and opened it in eclipse (with pydev) it does seem to want to play with me, changing the method to "getStreamKeyFromSongIDEx" get's me something, but then it returns a list, which apparently has no .iteritems

**Comment by gsteph** [comment]
heh guess I'm a lazy SoaB too!
What song do you test with (along with search query) ? could be song-specific. Who knows.

**Comment by DelusionalLogic** [comment]
should have known, i was wondering why it was showing everything as being changed.

woodlands by Rasmus Kellerman, the query i used it just "woodlands"

**Comment by gsteph** [comment]
Works great. Something is very wrong on your side.

**Comment by DelusionalLogic** [comment]
It must be, this is very strange. This is the return: {u'header': {u'prefetchEnabled': True, u'serviceVersion': u'20100903', u'session': u'21a9a6746a0dd27f4c283aa14c0d93d6'}, u'result': {u'24409048': []}} what a strange thing that it returns as if i was blocked.

I'll let it be till tomorrow, in case they made a new sort of ban they might only have banned the script (who knows) firefox seems to be banned to, chrome is untouched. by tomorrow i should be unbanned.

**Comment by gsteph** [comment]
Try deleting your chrome cache/cookies ?

**Comment by DelusionalLogic** [comment]
Nope, chrome still works, and python still fails, even worse, now the cookie monster is sad too.

Again, i'll see if it works tomorrow, i'll commit my changes when i get around to test it.

EDIT: Yep, it's because i'm "tempBanned" firefox doesn't work, so chrome uses another connection type than python and firefox? interesting.

**Comment by DelusionalLogic** [comment]
Yep, waiting the night fixed it.
